default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development:
  <<: *default
  database: microtasker_development

test:
  <<: *default
  database: microtasker_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
