default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  port: 3306
  host: localhost

development:
  <<: *default
  database: translate_dev
  username: root
  password:

test:
  <<: *default
  database: translate_test
  username: root
  password:

production:
  <<: *default
  database: translate_pro
  username: root
  password:
