development: &default
  adapter: mysql2
  username: root
  password: Hoang123456
  database: translate_dev
  encoding: utf8mb4

test:
  <<: *default
  database: translate_test
  encoding: utf8mb4

production:
  <<: *default
  database: translate_production
  encoding: utf8mb4
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
